export const WATCH_CANCEL_FRIENDSHIP = "WATCH_CANCEL_FRIENDSHIP";
export const WATCH_SET_INVITATION_DECISION = "WATCH_SET_INVITATION_DECISION";
export const WATCH_SEND_INVITATION = "WATCH_SET_INVITATION";
export const WATCH_GET_INVITATIONS = "WATCH_GET_INVITATIONS";
export const WATCH_FETCH_USER_FRIENDS = "WATCH_FETCH_USER_FRIENDS";
export const WATCH_FETCH_SHOPPING_LIST = "WATCH_FETCH_SHOPPING_LIST";
export const WATCH_CHANGE_USER_EMAIL = "WATCH_CHANGE_USER_EMAIL";
