export const WATCH_CANCEL_FRIENDSHIP = 'WATCH_CANCEL_FRIENDSHIP';
export const WATCH_SET_INVITATION_DECISION = 'WATCH_SET_INVITATION_DECISION';
export const WATCH_SEND_INVITATION = 'WATCH_SET_INVITATION';
